# Generated by Django 4.2.7 on 2025-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('employee_id', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=32)),
                ('subcategory', models.CharField(max_length=32)),
                ('priority', models.CharField(default='low', max_length=16)),
                ('status', models.CharField(default='open', max_length=16)),
                ('assigned_expert_id', models.CharField(blank=True, default='', max_length=64)),
                ('ai_solution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
