# Generated by Django 4.2.7 on 2025-09-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('expertise', models.JSONField(default=list)),
                ('contact', models.CharField(blank=True, default='', max_length=128)),
                ('availability', models.BooleanField(default=True)),
                ('current_load', models.IntegerField(default=0)),
            ],
        ),
    ]
